receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ":4317"

exporters:
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger]
